# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpi_motor_pb2 as rpi__motor__pb2


class RPIMotorStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetState = channel.unary_unary(
                '/omnirobotrpi.RPIMotor/SetState',
                request_serializer=rpi__motor__pb2.StateRequest.SerializeToString,
                response_deserializer=rpi__motor__pb2.StateReply.FromString,
                )


class RPIMotorServicer(object):
    """Interface exported by the server.
    """

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPIMotorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=rpi__motor__pb2.StateRequest.FromString,
                    response_serializer=rpi__motor__pb2.StateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnirobotrpi.RPIMotor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RPIMotor(object):
    """Interface exported by the server.
    """

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnirobotrpi.RPIMotor/SetState',
            rpi__motor__pb2.StateRequest.SerializeToString,
            rpi__motor__pb2.StateReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
