# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpi-motor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpi-motor.proto',
  package='omnirobotrpi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0frpi-motor.proto\x12\x0comnirobotrpi\";\n\x0cStateRequest\x12\r\n\x05vel_x\x18\x01 \x01(\x01\x12\r\n\x05vel_y\x18\x02 \x01(\x01\x12\r\n\x05vel_t\x18\x03 \x01(\x01\"\x19\n\nStateReply\x12\x0b\n\x03res\x18\x01 \x01(\x08\x32N\n\x08RPIMotor\x12\x42\n\x08SetState\x12\x1a.omnirobotrpi.StateRequest\x1a\x18.omnirobotrpi.StateReply\"\x00\x62\x06proto3'
)




_STATEREQUEST = _descriptor.Descriptor(
  name='StateRequest',
  full_name='omnirobotrpi.StateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vel_x', full_name='omnirobotrpi.StateRequest.vel_x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_y', full_name='omnirobotrpi.StateRequest.vel_y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_t', full_name='omnirobotrpi.StateRequest.vel_t', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=92,
)


_STATEREPLY = _descriptor.Descriptor(
  name='StateReply',
  full_name='omnirobotrpi.StateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='omnirobotrpi.StateReply.res', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['StateRequest'] = _STATEREQUEST
DESCRIPTOR.message_types_by_name['StateReply'] = _STATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateRequest = _reflection.GeneratedProtocolMessageType('StateRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEREQUEST,
  '__module__' : 'rpi_motor_pb2'
  # @@protoc_insertion_point(class_scope:omnirobotrpi.StateRequest)
  })
_sym_db.RegisterMessage(StateRequest)

StateReply = _reflection.GeneratedProtocolMessageType('StateReply', (_message.Message,), {
  'DESCRIPTOR' : _STATEREPLY,
  '__module__' : 'rpi_motor_pb2'
  # @@protoc_insertion_point(class_scope:omnirobotrpi.StateReply)
  })
_sym_db.RegisterMessage(StateReply)



_RPIMOTOR = _descriptor.ServiceDescriptor(
  name='RPIMotor',
  full_name='omnirobotrpi.RPIMotor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=121,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='omnirobotrpi.RPIMotor.SetState',
    index=0,
    containing_service=None,
    input_type=_STATEREQUEST,
    output_type=_STATEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPIMOTOR)

DESCRIPTOR.services_by_name['RPIMotor'] = _RPIMOTOR

# @@protoc_insertion_point(module_scope)
